//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressEntity
    {
        public AddressEntity()
        {
            this.Person = new HashSet<PersonEntity>();
        }
    
        public int ID { get; set; }
        public string Street { get; set; }
    
        public virtual ICollection<PersonEntity> Person { get; set; }
    }
}
